### ISSUE TITLE
Feature Request: Image Outputs for tz::ren

### ISSUE THREAD

**Issue by harrand** [harrand/Topaz#86]
**Describe the feature request**
tz::ren currently features `mesh_renderer` and `animation_renderer`. However, their underlying render target is not configurable (always being the swapchain images). If a game wanted to do some post-processing such as bloom then they would have to make local edits to these renderers.

Add a new constructor or setting to these classes, allowing them to optionally be passed an image output.

**Justification**
User should have as much control over the resultant render pipeline as possible. This shouldn't be hard to implement, just an oversight.

**Comment by uo246355** [comment]
Specimen #621 has shown promise, it has been able to hide from plain sight since last week, we foolishly thought he entered some kind of hibernative state, when my assistant entered to check on it directly it was ravaged.

Just an oversight.
